name: Example
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    name: Running unit test
    runs-on: ubuntu-latest

    steps:
    -uses: actions/checkout@v1
    -name: Use Node.js ${{ matrix.node-version}}
     uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}
     -name: install
     run: npm install
     -name: test
     run:npm test
